/***
***   This file is generated by JAIG at 22:10 26.02.2024
***   As a result of parsing GPT response 
***   prompt-response
***/
package app.test;

public class SimpleProgram {
    public static void main(String[] args) {
        System.out.println("hey you");
    }
}
